=== sarziv/php_environment/sites/html/Php_mysql/Xml_Lab_6/mok1/mok1.xsd
<?xml version="1.0" encoding="UTF-8"?> 
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Mokėjimai">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Organizacija" type="xs:string"/>
				<xs:element name="Data" type="xs:string"/>
				<xs:element name="Pavedimas" minOccurs="0" maxOccurs="unbounded" >
					<xs:complexType>
						<xs:sequence >
							<xs:element name="Sąskaita" type="xs:string" />
							<xs:element name="Gavėjas">
								<xs:complexType>
									<xs:sequence >
										<xs:element name="Pavadinimas" type="xs:string"/>
										<xs:element name="Bankas" type="xs:string"/>
										<xs:element name="Sąskaita" type="xs:string" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Suma">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:integer">
											<xs:attribute name="Valiuta" type="xs:string"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>	
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>	
		</xs:complexType>
	</xs:element>	
</xs:schema>

=== sarziv/php_environment/sites/html/Php_mysql/Xml_Lab_6/mok1/mok1.xml
<?xml version="1.0" encoding="UTF-8"?> 
<?xml-stylesheet type="text/xsl" href="mok1.xsl"?>
<Mokėjimai
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="mok1.xsd">
<Organizacija> KTU Informatikos fakultetas </Organizacija>
<Data>2017-05-25</Data>

<Pavedimas>
	<Sąskaita>S009 999</Sąskaita>
	<Gavėjas>
		<Pavadinimas>Mokesčių inspekcija</Pavadinimas>
		<Bankas>Swedbank</Bankas>
		<Sąskaita>9988 7766 55</Sąskaita>
	</Gavėjas>
	<Suma Valiuta="EUR">155.99</Suma>
</Pavedimas>
<Pavedimas>
	<Sąskaita>S009 907</Sąskaita>
	<Gavėjas>
		<Pavadinimas>Manchester Metropolitan University </Pavadinimas>
		<Bankas>Barclays Bank Delaware</Bankas>
		<Sąskaita>9988 7766 55</Sąskaita>
	</Gavėjas>
	<Suma Valiuta="GBP">212.55</Suma>
</Pavedimas>
<Pavedimas>
	<Sąskaita>S111 959</Sąskaita>
	<Gavėjas>
		<Pavadinimas>Šarūnas Živila</Pavadinimas>
		<Bankas>Swedbank</Bankas>
		<Sąskaita>3144 7226 55</Sąskaita>
	</Gavėjas>
	<Suma Valiuta="LT">25.81</Suma>
</Pavedimas>
</Mokėjimai>
